language: node_js

node_js:
  - 8.11.2

cache:
  directories:
    -"node_modules"

branches:
  only:
  - misha

install:
  - npm install

script:
  - npm run build
  - npm run eslint

deploy:
  provider: heroku
  app: "applicationradio"
  api_key:
    secure: "e44a4578-6bd2-403e-8a2b-d842fa375906"