sudo: false

language: node_js
node_js: -8

branches: only: -master

deploy: provider: heroku
app: applicationradio
api_key: secure: e44a4578-6bd2-403e-8a2b-d842fa375906

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js